name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                clean: false
                submodules: false        # We will handle this manually to avoid the error

            - name: Manual Submodule Sync
              run: |
                git config --global --add safe.directory '*'
                git submodule sync
                git submodule update --init --recursive assignment-autotest
                git submodule update --init buildroot

            - name: Run build
              timeout-minutes: 600
              run: |
                docker run --rm \
                -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                -w ${GITHUB_WORKSPACE} \
                -e FORCE_UNSAFE_CONFIGURE=1 \
                -e BR2_DOWNLOAD_FORCE_CHECK_HASHES= \
                cuaesd/aesd-autotest:24-assignment7 \
                bash -c "apt-get update && \
                     apt-get install -y file wget cpio rsync unzip bc && \
                     ./build.sh"

            - name: Run full test
              timeout-minutes: 60
              run: |
                 docker run --rm \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 -w ${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:24-assignment7 \
                 ./full-test.sh
