name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                clean: false
                submodules: false        # We will handle this manually to avoid the error

            - name: Manual Submodule Sync
              run: |
                git config --global --add safe.directory '*'
                git submodule sync
                git submodule update --init --recursive assignment-autotest
                git submodule update --init buildroot

            - name: Run build
              timeout-minutes: 600
              run: |
                docker run --rm \
                -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                -w ${GITHUB_WORKSPACE} \
                cuaesd/aesd-autotest:24-assignment7 \
                ./build.sh
